// Code generated by MockGen. DO NOT EDIT.
// Source: ./registrator.go

// Package testdata is a generated GoMock package.
package testdata

import (
	reflect "reflect"

	core "github.com/d34dl0ck/coupler/internal/core"
	gomock "github.com/golang/mock/gomock"
)

// MockRegistrator is a mock of Registrator interface.
type MockRegistrator struct {
	ctrl     *gomock.Controller
	recorder *MockRegistratorMockRecorder
}

// MockRegistratorMockRecorder is the mock recorder for MockRegistrator.
type MockRegistratorMockRecorder struct {
	mock *MockRegistrator
}

// NewMockRegistrator creates a new mock instance.
func NewMockRegistrator(ctrl *gomock.Controller) *MockRegistrator {
	mock := &MockRegistrator{ctrl: ctrl}
	mock.recorder = &MockRegistratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistrator) EXPECT() *MockRegistratorMockRecorder {
	return m.recorder
}

// Register mocks base method.
func (m *MockRegistrator) Register(k core.ResolvingKey, s core.ResolvingStrategy) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Register", k, s)
}

// Register indicates an expected call of Register.
func (mr *MockRegistratorMockRecorder) Register(k, s interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockRegistrator)(nil).Register), k, s)
}
